name: ContinuousTraining
on:
  push:
    branches:
      -workflow_continuous_training
  # Para que github action corra el worflow con este crontab, es decir cada 6 horas
  schedule:
    -cron:'0 */6 * * *'
  # Por si queremos correrlo manualmente
  workflow_dispatch:
    inputs:
      reason:
        description:Whytorunthis?
        required:false
        default:runningCT
# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write# need this for OIDC  
  contents: write
  pull-requests: write 
  issues: read
  packages: none
jobs:
  continuous-training:
    runs-on: ubuntu-latest
    steps:
      -name :Checkoutrepo
        uses: actions/checkout@v2
      -name: SetAWScredentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-session-name: aws_testing_session
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
      -name:Trainmodel
        run:|
          pip install pipenv
          pipenv install
          pipenv run python
          pip install -r src/requirements.txt
          dvc pull model/model.pkl.dvc -r model-track
          dvc unprotect model/model.pkl
          dvc repro -f 
          echo "Training Completed"
          dvc add model/model.pkl
          dvc push model/model.pkl -r model-track
# Running dvc unprotect guarantees that the target files or directories (targets) in the workspace are physically “unlinked” from the cache and can be safely updated. 
      -name: Commit.dvcfilechanges
        run: |
          git config --local user.email "oli@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add model/model.pkl.dvc
          git commit -m "Updating model serialization"
-uses:ad-m/github-push-action@master
        with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            branch: ${{github.ref}}
      -uses: iterative/setup-cml@v1
      -name: Pushmetrics
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run:|
          cat report.txt >> report.md 
          cml-publish prediction_behavior.png --md >> report.md
          cml-send-comment report.md